version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mitspieler
      POSTGRES_DB: lolpros

  app:
    restart: unless-stopped
    build: .

    ports: 
     - "5000:5000"

    volumes: 
     - .:/app

    depends_on:
     - db

  lolpros:
    build:
      context: .
      dockerfile: lolpros/Dockerfile
    
    volumes:
      - ./lolpros:/app

    depends_on:
      - db