version: "3.9"

services:
  db:
    restart: always
    image: postgres:13-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mitspieler
      POSTGRES_DB: lolpros

    ports:
      - "5432:5432"

    networks:
      - default

  app:
    restart: unless-stopped
    build: .

    networks:
      - caddy_enabled
      - default

    ports: 
     - "5000:5000"

    volumes: 
     - .:/app

    depends_on:
     - db

  lolpros:
    build:
      context: .
      dockerfile: lolpros/Dockerfile
    
    volumes:
      - ./lolpros:/app

    depends_on:
      - db

    networks:
      - default

networks:
  caddy_enabled:
     external: true
  default:

