version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mitspieler
      POSTGRES_DB: lolpros

    ports: 
    - "5432:5432"
